/**
 * Runtime loader for the committed GeoNames seed (server/seed/city-plans.json,
 * generated by scripts/build-city-plans.ts — CC BY 4.0 attribution in README).
 * Population + coordinates ride along: population drives the weighted random
 * city sampling, coordinates feed the dashboard globe when Places returns no
 * geometry.
 */

import { readFileSync } from 'node:fs'

export type PlanCity = {
  name: string
  /** US only: full state name — joins the search query for disambiguation. */
  admin1?: string
  lat: number
  lng: number
  population: number
}

type CityPlansSeed = {
  source: string
  generated_at: string
  countries: Record<string, { cities: PlanCity[] }>
}

const seed = JSON.parse(
  readFileSync(new URL('../seed/city-plans.json', import.meta.url), 'utf8'),
) as CityPlansSeed

export const CITY_PLANS: Record<string, { cities: readonly PlanCity[] }> = seed.countries
export const CITY_PLANS_SOURCE = seed.source

export function citiesOf(countryCode: string): readonly PlanCity[] {
  return CITY_PLANS[countryCode]?.cities ?? []
}
